### ISSUE TITLE
To activate trading, you must read and accept the Futures Trading User Agreement

### ISSUE THREAD

**Issue by Yihen** [jane-cloud/ok-open-api#6]
when I run the following statement, 
    futureAPI = future.FutureAPI(api_key, seceret_key, passphrase, True)
    result = futureAPI.get_accounts()

the exception thrower as followed:

{"code":32002,"message":"To activate trading, you must read and accept the Futures Trading User Agreement"}, 400

How to handle it? please help me.

**Comment by jane-cloud** [comment]
Need to go to the page to open the future contract    page and agree the agreement.
More problem can join this telegram group for consulting
https://t.me/OKExAPI

**Comment by Yihen** [comment]
Thanks. has been solved.
